language: python
python:
- '3.4'
install:
  pip install tox
script:
  tox -e $TOX_ENV
env:
  matrix:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
  global:
    - secure: dqz5GeC34d2WZCpvaeBOSdjv4gRZsqIZYvicdF/xeWft4FHFi3dTCed2jDTdQj3xUsE6nemWYWAgFM/f7ng0sLlE56dNqIwXRcpC7OYXKL/7lGQNuCDRVbDjMictvfVUohovugJx8KdaWj7abnh3AoDY4RpQ03sN2p17H06X6bo=
    - secure: I4LxO7VHb33Zmla/OXcxbO61tfHQ8OyeolsQxyP1oKeyB3adOCymwW3ReDWu4MlHYcOansBVtpM4JLFRSmsWTrDl2UrOjYASijtpcvF+P82b1Fv0Ln8WuVoMyXqnXgFntjfMNvpw+K3cIfWWnZHXPODGxoaxTjnIsnenN9j6kzM=
